package com.catify.processengine.core.messages;

/**
 * The trigger message is a signal to a process instance on a given node that
 * triggers further actions based on the implemented message reaction. Trigger
 * messages are usually generated by services (eg. message integration) and used
 * by catching events.
 * 
 * @author chris
 * 
 */
public class TriggerMessage extends Message {

	private static final long serialVersionUID = 1L;
	
	/** The payload. */
	private Object payload;

	/**
	 * Instantiates a new trigger message.
	 */
	public TriggerMessage() {
	}
	
	/**
	 * Instantiates a new trigger message.
	 *
	 * @param processInstanceId the process instance id
	 * @param data the data
	 */
	public TriggerMessage(String processInstanceId, Object data) {
		this.processInstanceId = processInstanceId;
		this.payload = data;
	}

	/**
	 * Gets the payload.
	 *
	 * @return the payload
	 */
	public Object getPayload() {
		return payload;
	}

	/**
	 * Sets the payload.
	 *
	 * @param payload the new payload
	 */
	public void setPayload(Object payload) {
		this.payload = payload;
	}
}
