/**
 * *******************************************************
 * Copyright (C) 2013 catify <info@catify.com>
 * *******************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.catify.processengine.core.messages;

/**
 * The wining message is generated by event based gateways. They send a winning
 * message to the catch event that triggered and arrived first at the event
 * based gateway.
 * 
 * @author christopher köster
 * 
 */
public class WinningMessage extends Message {

	/**
	 * Instantiates a new winning message.
	 */
	public WinningMessage() {
	}

	/**
	 * Instantiates a new winning message.
	 * 
	 * @param processInstanceId
	 *            the process instance id
	 */
	public WinningMessage(String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

}
