package com.catify.processengine.core.messages;

/**
 * The wining message is generated by event based gateways. They send a winning
 * message to the catch event that triggered and arrived first at the event
 * based gateway.
 * 
 * @author chris
 * 
 */
public class WinningMessage extends Message {

	/**
	 * Instantiates a new winning message.
	 */
	public WinningMessage() {
	}

	/**
	 * Instantiates a new winning message.
	 * 
	 * @param processInstanceId
	 *            the process instance id
	 */
	public WinningMessage(String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

}
