//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.23 at 04:42:49 PM MESZ 
//


package com.catify.processengine.core.processdefinition.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tMessageIntegrationDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tMessageIntegrationDirection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="implicit"/>
 *     &lt;enumeration value="in"/>
 *     &lt;enumeration value="out"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tMessageIntegrationDirection", namespace = "http://www.catify.com/processengine/core/processdefinition")
@XmlEnum
public enum TMessageIntegrationDirection {

    @XmlEnumValue("implicit")
    IMPLICIT("implicit"),
    @XmlEnumValue("in")
    IN("in"),
    @XmlEnumValue("out")
    OUT("out");
    private final String value;

    TMessageIntegrationDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TMessageIntegrationDirection fromValue(String v) {
        for (TMessageIntegrationDirection c: TMessageIntegrationDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
