<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2010

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_instance_BPMN20withoutDiagramms" select="."/>
		<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">
				<xsl:value-of select="'http://www.omg.org/spec/BPMN/20100524/MODEL C:/DOKUME~1/chris/Desktop/Dropbox/Masterarbeit/Code/Schema/internalBpmnSchema_007_RootElementDefenition.xsd'"/>
			</xsl:attribute>
			<xsl:for-each select="$var1_instance_BPMN20withoutDiagramms/ns0:definitions">
				<xsl:variable name="var2_definitions" select="."/>
				<xsl:if test="$var2_definitions/@id">
					<xsl:attribute name="id" namespace="">
						<xsl:value-of select="string($var2_definitions/@id)"/>
					</xsl:attribute>
				</xsl:if>
				<xsl:if test="$var2_definitions/@name">
					<xsl:attribute name="name" namespace="">
						<xsl:value-of select="string($var2_definitions/@name)"/>
					</xsl:attribute>
				</xsl:if>
				<xsl:for-each select="$var2_definitions/ns0:messageEventDefinition">
					<xsl:variable name="var4_messageEventDefinition" select="."/>
					<messageEventDefinition>
						<xsl:if test="$var4_messageEventDefinition/@id">
							<xsl:attribute name="id" namespace="">
								<xsl:value-of select="string($var4_messageEventDefinition/@id)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:for-each select="$var4_messageEventDefinition/ns0:extensionElements">
							<extensionElements/>
						</xsl:for-each>
						<xsl:for-each select="$var4_messageEventDefinition/ns0:operationRef">
							<xsl:variable name="var8_operationRef" select="."/>
							<operationRef>
								<xsl:value-of select="string($var8_operationRef)"/>
							</operationRef>
						</xsl:for-each>
					</messageEventDefinition>
				</xsl:for-each>
				<xsl:for-each select="$var2_definitions/ns0:process">
					<xsl:variable name="var10_process" select="."/>
					<process>
						<xsl:if test="$var10_process/@id">
							<xsl:attribute name="id" namespace="">
								<xsl:value-of select="string($var10_process/@id)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:if test="$var10_process/@name">
							<xsl:attribute name="name" namespace="">
								<xsl:value-of select="string($var10_process/@name)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:for-each select="$var10_process/ns0:extensionElements">
							<extensionElements/>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:complexGateway">
							<xsl:variable name="var14_complexGateway" select="."/>
							<complexGateway>
								<xsl:if test="$var14_complexGateway/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var14_complexGateway/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var14_complexGateway/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var14_complexGateway/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var14_complexGateway/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var14_complexGateway/ns0:incoming">
									<xsl:variable name="var18_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var18_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var14_complexGateway/ns0:outgoing">
									<xsl:variable name="var20_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var20_outgoing)"/>
									</outgoing>
								</xsl:for-each>
								<xsl:for-each select="$var14_complexGateway/ns0:activationCondition">
									<xsl:variable name="var22_activationCondition" select="."/>
									<activationCondition>
										<xsl:value-of select="string($var22_activationCondition)"/>
									</activationCondition>
								</xsl:for-each>
							</complexGateway>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:endEvent">
							<xsl:variable name="var24_endEvent" select="."/>
							<endEvent>
								<xsl:if test="$var24_endEvent/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var24_endEvent/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var24_endEvent/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var24_endEvent/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var24_endEvent/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var24_endEvent/ns0:incoming">
									<xsl:variable name="var28_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var28_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var24_endEvent/ns0:outgoing">
									<xsl:variable name="var30_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var30_outgoing)"/>
									</outgoing>
								</xsl:for-each>
								<xsl:for-each select="$var24_endEvent/ns0:messageEventDefinition">
									<xsl:variable name="var32_messageEventDefinition" select="."/>
									<messageEventDefinition>
										<xsl:if test="$var32_messageEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var32_messageEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var32_messageEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var32_messageEventDefinition/ns0:operationRef">
											<xsl:variable name="var36_operationRef" select="."/>
											<operationRef>
												<xsl:value-of select="string($var36_operationRef)"/>
											</operationRef>
										</xsl:for-each>
									</messageEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var24_endEvent/ns0:terminateEventDefinition">
									<xsl:variable name="var38_terminateEventDefinition" select="."/>
									<terminateEventDefinition>
										<xsl:if test="$var38_terminateEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var38_terminateEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var38_terminateEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</terminateEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var24_endEvent/ns0:eventDefinitionRef">
									<xsl:variable name="var42_eventDefinitionRef" select="."/>
									<eventDefinitionRef>
										<xsl:value-of select="string($var42_eventDefinitionRef)"/>
									</eventDefinitionRef>
								</xsl:for-each>
								<xsl:for-each select="$var24_endEvent/ns0:dataInput">
									<xsl:variable name="var44_dataInput" select="."/>
									<dataInput>
										<xsl:if test="$var44_dataInput/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var44_dataInput/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var44_dataInput/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</dataInput>
								</xsl:for-each>
							</endEvent>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:eventBasedGateway">
							<xsl:variable name="var48_eventBasedGateway" select="."/>
							<eventBasedGateway>
								<xsl:if test="$var48_eventBasedGateway/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var48_eventBasedGateway/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var48_eventBasedGateway/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var48_eventBasedGateway/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var48_eventBasedGateway/@eventGatewayType">
									<xsl:attribute name="eventGatewayType" namespace="">
										<xsl:value-of select="string($var48_eventBasedGateway/@eventGatewayType)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var48_eventBasedGateway/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var48_eventBasedGateway/ns0:incoming">
									<xsl:variable name="var52_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var52_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var48_eventBasedGateway/ns0:outgoing">
									<xsl:variable name="var54_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var54_outgoing)"/>
									</outgoing>
								</xsl:for-each>
							</eventBasedGateway>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:exclusiveGateway">
							<xsl:variable name="var56_exclusiveGateway" select="."/>
							<exclusiveGateway>
								<xsl:if test="$var56_exclusiveGateway/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var56_exclusiveGateway/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var56_exclusiveGateway/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var56_exclusiveGateway/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var56_exclusiveGateway/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var56_exclusiveGateway/ns0:incoming">
									<xsl:variable name="var60_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var60_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var56_exclusiveGateway/ns0:outgoing">
									<xsl:variable name="var62_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var62_outgoing)"/>
									</outgoing>
								</xsl:for-each>
							</exclusiveGateway>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:intermediateCatchEvent">
							<xsl:variable name="var64_intermediateCatchEvent" select="."/>
							<intermediateCatchEvent>
								<xsl:if test="$var64_intermediateCatchEvent/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var64_intermediateCatchEvent/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var64_intermediateCatchEvent/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var64_intermediateCatchEvent/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:incoming">
									<xsl:variable name="var68_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var68_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:outgoing">
									<xsl:variable name="var70_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var70_outgoing)"/>
									</outgoing>
								</xsl:for-each>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:messageEventDefinition">
									<xsl:variable name="var72_messageEventDefinition" select="."/>
									<messageEventDefinition>
										<xsl:if test="$var72_messageEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var72_messageEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var72_messageEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var72_messageEventDefinition/ns0:operationRef">
											<xsl:variable name="var76_operationRef" select="."/>
											<operationRef>
												<xsl:value-of select="string($var76_operationRef)"/>
											</operationRef>
										</xsl:for-each>
									</messageEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:terminateEventDefinition">
									<xsl:variable name="var78_terminateEventDefinition" select="."/>
									<terminateEventDefinition>
										<xsl:if test="$var78_terminateEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var78_terminateEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var78_terminateEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</terminateEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:eventDefinitionRef">
									<xsl:variable name="var82_eventDefinitionRef" select="."/>
									<eventDefinitionRef>
										<xsl:value-of select="string($var82_eventDefinitionRef)"/>
									</eventDefinitionRef>
								</xsl:for-each>
								<xsl:for-each select="$var64_intermediateCatchEvent/ns0:dataOutput">
									<xsl:variable name="var84_dataOutput" select="."/>
									<dataOutput>
										<xsl:if test="$var84_dataOutput/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var84_dataOutput/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var84_dataOutput/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</dataOutput>
								</xsl:for-each>
							</intermediateCatchEvent>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:intermediateThrowEvent">
							<xsl:variable name="var88_intermediateThrowEvent" select="."/>
							<intermediateThrowEvent>
								<xsl:if test="$var88_intermediateThrowEvent/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var88_intermediateThrowEvent/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var88_intermediateThrowEvent/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var88_intermediateThrowEvent/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:incoming">
									<xsl:variable name="var92_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var92_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:outgoing">
									<xsl:variable name="var94_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var94_outgoing)"/>
									</outgoing>
								</xsl:for-each>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:messageEventDefinition">
									<xsl:variable name="var96_messageEventDefinition" select="."/>
									<messageEventDefinition>
										<xsl:if test="$var96_messageEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var96_messageEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var96_messageEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var96_messageEventDefinition/ns0:operationRef">
											<xsl:variable name="var100_operationRef" select="."/>
											<operationRef>
												<xsl:value-of select="string($var100_operationRef)"/>
											</operationRef>
										</xsl:for-each>
									</messageEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:terminateEventDefinition">
									<xsl:variable name="var102_terminateEventDefinition" select="."/>
									<terminateEventDefinition>
										<xsl:if test="$var102_terminateEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var102_terminateEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var102_terminateEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</terminateEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:eventDefinitionRef">
									<xsl:variable name="var106_eventDefinitionRef" select="."/>
									<eventDefinitionRef>
										<xsl:value-of select="string($var106_eventDefinitionRef)"/>
									</eventDefinitionRef>
								</xsl:for-each>
								<xsl:for-each select="$var88_intermediateThrowEvent/ns0:dataInput">
									<xsl:variable name="var108_dataInput" select="."/>
									<dataInput>
										<xsl:if test="$var108_dataInput/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var108_dataInput/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var108_dataInput/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</dataInput>
								</xsl:for-each>
							</intermediateThrowEvent>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:parallelGateway">
							<xsl:variable name="var112_parallelGateway" select="."/>
							<parallelGateway>
								<xsl:if test="$var112_parallelGateway/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var112_parallelGateway/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var112_parallelGateway/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var112_parallelGateway/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var112_parallelGateway/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var112_parallelGateway/ns0:incoming">
									<xsl:variable name="var116_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var116_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var112_parallelGateway/ns0:outgoing">
									<xsl:variable name="var118_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var118_outgoing)"/>
									</outgoing>
								</xsl:for-each>
							</parallelGateway>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:sequenceFlow">
							<xsl:variable name="var120_sequenceFlow" select="."/>
							<sequenceFlow>
								<xsl:if test="$var120_sequenceFlow/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var120_sequenceFlow/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var120_sequenceFlow/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var120_sequenceFlow/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:attribute name="sourceRef" namespace="">
									<xsl:value-of select="string($var120_sequenceFlow/@sourceRef)"/>
								</xsl:attribute>
								<xsl:attribute name="targetRef" namespace="">
									<xsl:value-of select="string($var120_sequenceFlow/@targetRef)"/>
								</xsl:attribute>
								<xsl:for-each select="$var120_sequenceFlow/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
							</sequenceFlow>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:serviceTask">
							<xsl:variable name="var124_serviceTask" select="."/>
							<serviceTask>
								<xsl:if test="$var124_serviceTask/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var124_serviceTask/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var124_serviceTask/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var124_serviceTask/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var124_serviceTask/@implementation">
									<xsl:attribute name="implementation" namespace="">
										<xsl:value-of select="string($var124_serviceTask/@implementation)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var124_serviceTask/@operationRef">
									<xsl:attribute name="operationRef" namespace="">
										<xsl:value-of select="string($var124_serviceTask/@operationRef)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var124_serviceTask/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var124_serviceTask/ns0:incoming">
									<xsl:variable name="var128_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var128_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var124_serviceTask/ns0:outgoing">
									<xsl:variable name="var130_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var130_outgoing)"/>
									</outgoing>
								</xsl:for-each>
							</serviceTask>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:startEvent">
							<xsl:variable name="var132_startEvent" select="."/>
							<startEvent>
								<xsl:if test="$var132_startEvent/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var132_startEvent/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var132_startEvent/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var132_startEvent/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var132_startEvent/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var132_startEvent/ns0:incoming">
									<xsl:variable name="var136_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var136_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var132_startEvent/ns0:outgoing">
									<xsl:variable name="var138_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var138_outgoing)"/>
									</outgoing>
								</xsl:for-each>
								<xsl:for-each select="$var132_startEvent/ns0:messageEventDefinition">
									<xsl:variable name="var140_messageEventDefinition" select="."/>
									<messageEventDefinition>
										<xsl:if test="$var140_messageEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var140_messageEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var140_messageEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var140_messageEventDefinition/ns0:operationRef">
											<xsl:variable name="var144_operationRef" select="."/>
											<operationRef>
												<xsl:value-of select="string($var144_operationRef)"/>
											</operationRef>
										</xsl:for-each>
									</messageEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var132_startEvent/ns0:terminateEventDefinition">
									<xsl:variable name="var146_terminateEventDefinition" select="."/>
									<terminateEventDefinition>
										<xsl:if test="$var146_terminateEventDefinition/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var146_terminateEventDefinition/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var146_terminateEventDefinition/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</terminateEventDefinition>
								</xsl:for-each>
								<xsl:for-each select="$var132_startEvent/ns0:eventDefinitionRef">
									<xsl:variable name="var150_eventDefinitionRef" select="."/>
									<eventDefinitionRef>
										<xsl:value-of select="string($var150_eventDefinitionRef)"/>
									</eventDefinitionRef>
								</xsl:for-each>
								<xsl:for-each select="$var132_startEvent/ns0:dataOutput">
									<xsl:variable name="var152_dataOutput" select="."/>
									<dataOutput>
										<xsl:if test="$var152_dataOutput/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var152_dataOutput/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var152_dataOutput/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</dataOutput>
								</xsl:for-each>
							</startEvent>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:subProcess">
							<xsl:variable name="var156_subProcess" select="."/>
							<subProcess>
								<xsl:if test="$var156_subProcess/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var156_subProcess/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var156_subProcess/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var156_subProcess/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var156_subProcess/@triggeredByEvent">
									<xsl:attribute name="triggeredByEvent" namespace="">
										<xsl:value-of select="(('0' != normalize-space($var156_subProcess/@triggeredByEvent)) and ('false' != normalize-space($var156_subProcess/@triggeredByEvent)))"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var156_subProcess/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:incoming">
									<xsl:variable name="var160_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var160_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:outgoing">
									<xsl:variable name="var162_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var162_outgoing)"/>
									</outgoing>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:complexGateway">
									<xsl:variable name="var164_complexGateway" select="."/>
									<complexGateway>
										<xsl:if test="$var164_complexGateway/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var164_complexGateway/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var164_complexGateway/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var164_complexGateway/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var164_complexGateway/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var164_complexGateway/ns0:incoming">
											<xsl:variable name="var168_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var168_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var164_complexGateway/ns0:outgoing">
											<xsl:variable name="var170_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var170_outgoing)"/>
											</outgoing>
										</xsl:for-each>
										<xsl:for-each select="$var164_complexGateway/ns0:activationCondition">
											<xsl:variable name="var172_activationCondition" select="."/>
											<activationCondition>
												<xsl:value-of select="string($var172_activationCondition)"/>
											</activationCondition>
										</xsl:for-each>
									</complexGateway>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:endEvent">
									<xsl:variable name="var174_endEvent" select="."/>
									<endEvent>
										<xsl:if test="$var174_endEvent/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var174_endEvent/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var174_endEvent/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var174_endEvent/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var174_endEvent/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var174_endEvent/ns0:incoming">
											<xsl:variable name="var178_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var178_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var174_endEvent/ns0:outgoing">
											<xsl:variable name="var180_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var180_outgoing)"/>
											</outgoing>
										</xsl:for-each>
										<xsl:for-each select="$var174_endEvent/ns0:messageEventDefinition">
											<xsl:variable name="var182_messageEventDefinition" select="."/>
											<messageEventDefinition>
												<xsl:if test="$var182_messageEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var182_messageEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var182_messageEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
												<xsl:for-each select="$var182_messageEventDefinition/ns0:operationRef">
													<xsl:variable name="var186_operationRef" select="."/>
													<operationRef>
														<xsl:value-of select="string($var186_operationRef)"/>
													</operationRef>
												</xsl:for-each>
											</messageEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var174_endEvent/ns0:terminateEventDefinition">
											<xsl:variable name="var188_terminateEventDefinition" select="."/>
											<terminateEventDefinition>
												<xsl:if test="$var188_terminateEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var188_terminateEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var188_terminateEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</terminateEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var174_endEvent/ns0:eventDefinitionRef">
											<xsl:variable name="var192_eventDefinitionRef" select="."/>
											<eventDefinitionRef>
												<xsl:value-of select="string($var192_eventDefinitionRef)"/>
											</eventDefinitionRef>
										</xsl:for-each>
										<xsl:for-each select="$var174_endEvent/ns0:dataInput">
											<xsl:variable name="var194_dataInput" select="."/>
											<dataInput>
												<xsl:if test="$var194_dataInput/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var194_dataInput/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var194_dataInput/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</dataInput>
										</xsl:for-each>
									</endEvent>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:eventBasedGateway">
									<xsl:variable name="var198_eventBasedGateway" select="."/>
									<eventBasedGateway>
										<xsl:if test="$var198_eventBasedGateway/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var198_eventBasedGateway/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var198_eventBasedGateway/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var198_eventBasedGateway/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var198_eventBasedGateway/@eventGatewayType">
											<xsl:attribute name="eventGatewayType" namespace="">
												<xsl:value-of select="string($var198_eventBasedGateway/@eventGatewayType)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var198_eventBasedGateway/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var198_eventBasedGateway/ns0:incoming">
											<xsl:variable name="var202_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var202_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var198_eventBasedGateway/ns0:outgoing">
											<xsl:variable name="var204_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var204_outgoing)"/>
											</outgoing>
										</xsl:for-each>
									</eventBasedGateway>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:exclusiveGateway">
									<xsl:variable name="var206_exclusiveGateway" select="."/>
									<exclusiveGateway>
										<xsl:if test="$var206_exclusiveGateway/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var206_exclusiveGateway/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var206_exclusiveGateway/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var206_exclusiveGateway/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var206_exclusiveGateway/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var206_exclusiveGateway/ns0:incoming">
											<xsl:variable name="var210_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var210_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var206_exclusiveGateway/ns0:outgoing">
											<xsl:variable name="var212_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var212_outgoing)"/>
											</outgoing>
										</xsl:for-each>
									</exclusiveGateway>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:intermediateCatchEvent">
									<xsl:variable name="var214_intermediateCatchEvent" select="."/>
									<intermediateCatchEvent>
										<xsl:if test="$var214_intermediateCatchEvent/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var214_intermediateCatchEvent/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var214_intermediateCatchEvent/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var214_intermediateCatchEvent/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:incoming">
											<xsl:variable name="var218_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var218_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:outgoing">
											<xsl:variable name="var220_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var220_outgoing)"/>
											</outgoing>
										</xsl:for-each>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:messageEventDefinition">
											<xsl:variable name="var222_messageEventDefinition" select="."/>
											<messageEventDefinition>
												<xsl:if test="$var222_messageEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var222_messageEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var222_messageEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
												<xsl:for-each select="$var222_messageEventDefinition/ns0:operationRef">
													<xsl:variable name="var226_operationRef" select="."/>
													<operationRef>
														<xsl:value-of select="string($var226_operationRef)"/>
													</operationRef>
												</xsl:for-each>
											</messageEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:terminateEventDefinition">
											<xsl:variable name="var228_terminateEventDefinition" select="."/>
											<terminateEventDefinition>
												<xsl:if test="$var228_terminateEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var228_terminateEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var228_terminateEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</terminateEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:eventDefinitionRef">
											<xsl:variable name="var232_eventDefinitionRef" select="."/>
											<eventDefinitionRef>
												<xsl:value-of select="string($var232_eventDefinitionRef)"/>
											</eventDefinitionRef>
										</xsl:for-each>
										<xsl:for-each select="$var214_intermediateCatchEvent/ns0:dataOutput">
											<xsl:variable name="var234_dataOutput" select="."/>
											<dataOutput>
												<xsl:if test="$var234_dataOutput/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var234_dataOutput/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var234_dataOutput/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</dataOutput>
										</xsl:for-each>
									</intermediateCatchEvent>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:intermediateThrowEvent">
									<xsl:variable name="var238_intermediateThrowEvent" select="."/>
									<intermediateThrowEvent>
										<xsl:if test="$var238_intermediateThrowEvent/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var238_intermediateThrowEvent/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var238_intermediateThrowEvent/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var238_intermediateThrowEvent/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:incoming">
											<xsl:variable name="var242_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var242_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:outgoing">
											<xsl:variable name="var244_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var244_outgoing)"/>
											</outgoing>
										</xsl:for-each>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:messageEventDefinition">
											<xsl:variable name="var246_messageEventDefinition" select="."/>
											<messageEventDefinition>
												<xsl:if test="$var246_messageEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var246_messageEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var246_messageEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
												<xsl:for-each select="$var246_messageEventDefinition/ns0:operationRef">
													<xsl:variable name="var250_operationRef" select="."/>
													<operationRef>
														<xsl:value-of select="string($var250_operationRef)"/>
													</operationRef>
												</xsl:for-each>
											</messageEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:terminateEventDefinition">
											<xsl:variable name="var252_terminateEventDefinition" select="."/>
											<terminateEventDefinition>
												<xsl:if test="$var252_terminateEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var252_terminateEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var252_terminateEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</terminateEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:eventDefinitionRef">
											<xsl:variable name="var256_eventDefinitionRef" select="."/>
											<eventDefinitionRef>
												<xsl:value-of select="string($var256_eventDefinitionRef)"/>
											</eventDefinitionRef>
										</xsl:for-each>
										<xsl:for-each select="$var238_intermediateThrowEvent/ns0:dataInput">
											<xsl:variable name="var258_dataInput" select="."/>
											<dataInput>
												<xsl:if test="$var258_dataInput/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var258_dataInput/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var258_dataInput/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</dataInput>
										</xsl:for-each>
									</intermediateThrowEvent>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:parallelGateway">
									<xsl:variable name="var262_parallelGateway" select="."/>
									<parallelGateway>
										<xsl:if test="$var262_parallelGateway/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var262_parallelGateway/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var262_parallelGateway/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var262_parallelGateway/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var262_parallelGateway/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var262_parallelGateway/ns0:incoming">
											<xsl:variable name="var266_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var266_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var262_parallelGateway/ns0:outgoing">
											<xsl:variable name="var268_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var268_outgoing)"/>
											</outgoing>
										</xsl:for-each>
									</parallelGateway>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:sequenceFlow">
									<xsl:variable name="var270_sequenceFlow" select="."/>
									<sequenceFlow>
										<xsl:if test="$var270_sequenceFlow/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var270_sequenceFlow/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var270_sequenceFlow/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var270_sequenceFlow/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:attribute name="sourceRef" namespace="">
											<xsl:value-of select="string($var270_sequenceFlow/@sourceRef)"/>
										</xsl:attribute>
										<xsl:attribute name="targetRef" namespace="">
											<xsl:value-of select="string($var270_sequenceFlow/@targetRef)"/>
										</xsl:attribute>
										<xsl:for-each select="$var270_sequenceFlow/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
									</sequenceFlow>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:serviceTask">
									<xsl:variable name="var274_serviceTask" select="."/>
									<serviceTask>
										<xsl:if test="$var274_serviceTask/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var274_serviceTask/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var274_serviceTask/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var274_serviceTask/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var274_serviceTask/@implementation">
											<xsl:attribute name="implementation" namespace="">
												<xsl:value-of select="string($var274_serviceTask/@implementation)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var274_serviceTask/@operationRef">
											<xsl:attribute name="operationRef" namespace="">
												<xsl:value-of select="string($var274_serviceTask/@operationRef)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var274_serviceTask/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var274_serviceTask/ns0:incoming">
											<xsl:variable name="var278_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var278_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var274_serviceTask/ns0:outgoing">
											<xsl:variable name="var280_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var280_outgoing)"/>
											</outgoing>
										</xsl:for-each>
									</serviceTask>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:startEvent">
									<xsl:variable name="var282_startEvent" select="."/>
									<startEvent>
										<xsl:if test="$var282_startEvent/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var282_startEvent/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var282_startEvent/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var282_startEvent/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var282_startEvent/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var282_startEvent/ns0:incoming">
											<xsl:variable name="var286_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var286_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var282_startEvent/ns0:outgoing">
											<xsl:variable name="var288_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var288_outgoing)"/>
											</outgoing>
										</xsl:for-each>
										<xsl:for-each select="$var282_startEvent/ns0:messageEventDefinition">
											<xsl:variable name="var290_messageEventDefinition" select="."/>
											<messageEventDefinition>
												<xsl:if test="$var290_messageEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var290_messageEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var290_messageEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
												<xsl:for-each select="$var290_messageEventDefinition/ns0:operationRef">
													<xsl:variable name="var294_operationRef" select="."/>
													<operationRef>
														<xsl:value-of select="string($var294_operationRef)"/>
													</operationRef>
												</xsl:for-each>
											</messageEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var282_startEvent/ns0:terminateEventDefinition">
											<xsl:variable name="var296_terminateEventDefinition" select="."/>
											<terminateEventDefinition>
												<xsl:if test="$var296_terminateEventDefinition/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var296_terminateEventDefinition/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var296_terminateEventDefinition/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</terminateEventDefinition>
										</xsl:for-each>
										<xsl:for-each select="$var282_startEvent/ns0:eventDefinitionRef">
											<xsl:variable name="var300_eventDefinitionRef" select="."/>
											<eventDefinitionRef>
												<xsl:value-of select="string($var300_eventDefinitionRef)"/>
											</eventDefinitionRef>
										</xsl:for-each>
										<xsl:for-each select="$var282_startEvent/ns0:dataOutput">
											<xsl:variable name="var302_dataOutput" select="."/>
											<dataOutput>
												<xsl:if test="$var302_dataOutput/@id">
													<xsl:attribute name="id" namespace="">
														<xsl:value-of select="string($var302_dataOutput/@id)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:for-each select="$var302_dataOutput/ns0:extensionElements">
													<extensionElements/>
												</xsl:for-each>
											</dataOutput>
										</xsl:for-each>
									</startEvent>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:subProcess">
									<subProcess/>
								</xsl:for-each>
								<xsl:for-each select="$var156_subProcess/ns0:task">
									<xsl:variable name="var308_task" select="."/>
									<task>
										<xsl:if test="$var308_task/@id">
											<xsl:attribute name="id" namespace="">
												<xsl:value-of select="string($var308_task/@id)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:if test="$var308_task/@name">
											<xsl:attribute name="name" namespace="">
												<xsl:value-of select="string($var308_task/@name)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:for-each select="$var308_task/ns0:extensionElements">
											<extensionElements/>
										</xsl:for-each>
										<xsl:for-each select="$var308_task/ns0:incoming">
											<xsl:variable name="var312_incoming" select="."/>
											<incoming>
												<xsl:value-of select="string($var312_incoming)"/>
											</incoming>
										</xsl:for-each>
										<xsl:for-each select="$var308_task/ns0:outgoing">
											<xsl:variable name="var314_outgoing" select="."/>
											<outgoing>
												<xsl:value-of select="string($var314_outgoing)"/>
											</outgoing>
										</xsl:for-each>
									</task>
								</xsl:for-each>
							</subProcess>
						</xsl:for-each>
						<xsl:for-each select="$var10_process/ns0:task">
							<xsl:variable name="var316_task" select="."/>
							<task>
								<xsl:if test="$var316_task/@id">
									<xsl:attribute name="id" namespace="">
										<xsl:value-of select="string($var316_task/@id)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:if test="$var316_task/@name">
									<xsl:attribute name="name" namespace="">
										<xsl:value-of select="string($var316_task/@name)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:for-each select="$var316_task/ns0:extensionElements">
									<extensionElements/>
								</xsl:for-each>
								<xsl:for-each select="$var316_task/ns0:incoming">
									<xsl:variable name="var320_incoming" select="."/>
									<incoming>
										<xsl:value-of select="string($var320_incoming)"/>
									</incoming>
								</xsl:for-each>
								<xsl:for-each select="$var316_task/ns0:outgoing">
									<xsl:variable name="var322_outgoing" select="."/>
									<outgoing>
										<xsl:value-of select="string($var322_outgoing)"/>
									</outgoing>
								</xsl:for-each>
							</task>
						</xsl:for-each>
					</process>
				</xsl:for-each>
				<xsl:for-each select="$var2_definitions/ns0:terminateEventDefinition">
					<xsl:variable name="var324_terminateEventDefinition" select="."/>
					<terminateEventDefinition>
						<xsl:if test="$var324_terminateEventDefinition/@id">
							<xsl:attribute name="id" namespace="">
								<xsl:value-of select="string($var324_terminateEventDefinition/@id)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:for-each select="$var324_terminateEventDefinition/ns0:extensionElements">
							<extensionElements/>
						</xsl:for-each>
					</terminateEventDefinition>
				</xsl:for-each>
			</xsl:for-each>
		</definitions>
	</xsl:template>
</xsl:stylesheet>
